/*
  Ταμεία
  © 2026 Ανδρέας Μ. Γλεντζάκης (Andreas M. Glentzakis). Με την επιφύλαξη παντός δικαιώματος. All rights reserved.
  Απαγορεύεται η αντιγραφή, τροποποίηση και διάθεση, εν όλω ή εν μέρει, χωρίς προηγούμενη γραπτή άδεια του κατόχου.
  Copying, modification and distribution, in whole or in part, without the owner's prior written permission are prohibited.
*/
const rcAmts=t=>{const n=[],o=/(\d{1,3}(?:[.\s]\d{3})+[.,]\d{2}|\d+[.,]\d{2})(?!\d)/g;let e;for(;e=o.exec(t);)n.push(atNum(e[1].replace(/\s/g,"")));return n.filter(a=>a!=null&&a>0)};function rcParse(t){const n=String(t||"").replace(/\r/g,""),o=n.split(`
`).map(s=>s.replace(/\s+/g," ").trim()).filter(Boolean),e=o.map(s=>norm(s));let a=0;const i=[/πληρωτε|συνολο πληρωμ|γενικο συνολο|ποσο πληρωμ|πληρωμη με καρτα/,/(^|\s)(συνολο|συν\.|total|συνολικο)/];for(const s of i){for(let c=e.length-1;c>=0;c--){if(!s.test(e[c])||/υποσυνολ|συνολο φπα|φ\.?π\.?α\.?\s*$|καθαρ/.test(e[c]))continue;const r=rcAmts(o[c]),f=r.length?r[r.length-1]:rcAmts(o[c+1]||"")[0]||0;if(f>0){a=f;break}}if(a)break}if(!a){const s=rcAmts(n);a=s.length?Math.max(...s):0}let l="";{const s=norm(n).replace(/\s+/g," ");let c=/α\.?\s?φ\.?\s?μ\.?\s*[:.]?\s*(\d{9})(?!\d)/.exec(s)||/(?:vat|afm)\s*(?:no)?\s*[:.]?\s*(?:el)?\s*(\d{9})(?!\d)/.exec(s);c?l=c[1]:l=(n.match(/(?<!\d)\d{9}(?!\d)/g)||[]).find(afmOk)||""}let m=null;{const s=/(\d{1,2})[\/.\-](\d{1,2})[\/.\-](\d{2,4})/g;let c;for(;c=s.exec(n);){let r=+c[3];r<100&&(r+=2e3);const f=new Date(r,+c[2]-1,+c[1],12);if(+c[2]>=1&&+c[2]<=12&&+c[1]>=1&&+c[1]<=31&&!isNaN(f)&&f-Date.now()<864e5&&r>2e3){m=f;break}}}const d=(o.find((s,c)=>{const r=e[c];return/[a-zα-ω]{3}/.test(r)&&!/α\.?φ\.?μ|δ\.?ο\.?υ|τηλ|φαξ|fax|www|http|@|αποδειξη|τιμολογιο|λιανικ|καλως|ευχαριστ|ημερομ|ωρα|ταμει|δελτιο|αρ\.|α\/α|οδος|λεωφ|τ\.?κ\.?\s*\d/.test(r)})||"").replace(/[^A-Za-zΑ-Ωα-ωΆ-Ώά-ώ0-9&.,'\- ]/g,"").trim().slice(0,40),h=[...new Set((n.match(/(?<!\d)(24|13|6)\s?%/g)||[]).map(s=>parseInt(s)))],p=h.length===1?h[0]:null,g=norm(n),b=/τιμολογιο/.test(g)?"inv":/παροχης υπηρεσιων|παροχ\.?\s*υπηρ/.test(g)?"srv":/αποδειξη|λιανικ/.test(g)?"rcpt":"";let u="";{const s=/(?:αρ\.?\s*παρ\S*|αριθμος|α\/α|no\.?)\s*[:.]?\s*([a-zα-ω]{0,3}[\-\s]?\d{1,8})/i.exec(norm(n));s&&(u=s[1].toUpperCase().replace(/\s/g,""))}return{amount:rnd(a),afm:l,date:m,shop:d,vat:p,doc:b,docno:u,lines:o.length}}async function rcImage(t){const n=URL.createObjectURL(t);try{const o=await new Promise((l,m)=>{const d=new Image;d.onload=()=>l(d),d.onerror=m,d.src=n}),e=Math.min(1,1800/Math.max(o.width,o.height)),a=document.createElement("canvas");a.width=Math.round(o.width*e),a.height=Math.round(o.height*e);const i=a.getContext("2d");return i.filter="grayscale(1) contrast(1.35)",i.drawImage(o,0,0,a.width,a.height),a}finally{URL.revokeObjectURL(n)}}async function rcOcr(t,n){if(window.rcOcrHook)return await window.rcOcrHook(t);if(!window.Tesseract)try{await kxLoadScript(KX_TESS)}catch{throw new Error("net")}const o=await Tesseract.createWorker("ell+eng",1,{logger:e=>{e&&e.status==="recognizing text"&&n&&n(e.progress)}});try{const e=await rcImage(t);return(await o.recognize(e)).data.text||""}finally{try{await o.terminate()}catch{}}}function rcSheet(t){t=t||"out",openSheet({title:"📷 "+T("Φωτογραφία απόδειξης"),cancelLabel:T("Άκυρο"),onCancel:()=>{typeof pNewFlow=="function"&&pNewFlow(t)},body:`<p class="note" style="margin-top:0">${T("Φωτογράφισε την απόδειξη ίσια, να φαίνεται ολόκληρη και καθαρά. Η εφαρμογή βρίσκει το σύνολο, την ημερομηνία, το κατάστημα και τον ΑΦΜ, και ανοίγει έτοιμη την κίνηση για έλεγχο.")}</p>
      <div class="rcbtns"><label class="btn amber wide filebtn">📷 ${T("Φωτογράφισε")}<input type="file" id="rc_cam" accept="image/*" capture="environment" hidden></label>
      <label class="btn ghost wide filebtn" style="border:1.5px solid var(--line)">🖼 ${T("Από τη συλλογή")}<input type="file" id="rc_gal" accept="image/*" hidden></label></div>
      <div id="rc_st" class="note" style="text-align:center;font-weight:700"></div>
      <p class="note">🔒 ${T("Η ανάγνωση γίνεται μέσα στο κινητό. Η φωτογραφία δεν φυλάγεται και δεν στέλνεται πουθενά. Την πρώτη φορά κατεβαίνουν τα γράμματα της ανάγνωσης (θέλει διαδίκτυο).")}</p>`});const n=async o=>{const e=o.target.files&&o.target.files[0];if(o.target.value="",!e)return;const a=$("#rc_st");a&&(a.textContent="⏳ "+T("Διαβάζω την απόδειξη…"));try{const i=await rcOcr(e,l=>{a&&(a.textContent="⏳ "+T("Διαβάζω την απόδειξη…")+" "+Math.round(l*100)+"%")});rcOpen(rcParse(i),t)}catch(i){a&&(a.textContent=""),toast(i&&i.message==="net"?T("Η ανάγνωση θέλει διαδίκτυο την πρώτη φορά."):T("Η απόδειξη δεν διαβάστηκε. Δοκίμασε πιο καθαρή φωτογραφία."))}};$("#rc_cam").onchange=n,$("#rc_gal").onchange=n}function rcOpen(t,n){t.amount>0||toast(T("Δεν βρέθηκε ποσό στην απόδειξη. Δοκίμασε πιο καθαρή φωτογραφία ή γράψε το ποσό."));const o=t.shop&&typeof voMatch=="function"?voMatch(t.shop,n):null,e={kind:o?o.kind:null,sub:o?o.sub:"",amount:t.amount>0?t.amount.toFixed(2).replace(".",","):"",date:(t.date||new Date).toISOString(),note:t.shop||"",__fresh:!0,__back:()=>rcSheet(n)};t.afm&&(e.afm=t.afm),t.shop&&(e.cp=t.shop),t.vat!=null&&(e.vat=t.vat),t.doc&&(e.doc=t.doc),t.docno&&(e.docno=t.docno),closeSheet(),pEntryForm(null,n,e),setTimeout(()=>{const a=$("#shBody");a&&!a.querySelector(".rcnote")&&a.insertAdjacentHTML("afterbegin",`<p class="note rcnote" style="margin-top:0">📷 ${T("Από την απόδειξη. Έλεγξε το ποσό και την κατηγορία και πάτα «Καταχώρηση».")}${t.afm?" · "+T("ΑΦΜ")+" "+esc(t.afm):""}</p>`)},30)}const rcBtnHTML=t=>`<button type="button" class="vobtn rcbtn" data-receipt="${t}"><span class="vomi">📷</span><span><b>${T("Φωτογραφία απόδειξης")}</b><small>${T("διαβάζει ποσό, ημερομηνία, κατάστημα, ΑΦΜ")}</small></span></button>`;document.addEventListener("click",t=>{const n=t.target.closest&&t.target.closest("[data-receipt]");n&&(t.stopImmediatePropagation(),t.preventDefault(),rcSheet(n.dataset.receipt))},!0),(()=>{const t=document.createElement("style");t.textContent=`.rcbtns{display:grid;gap:8px;margin:6px 0 8px}.rcbtns .btn{width:100%;justify-content:center}
.vobtn.rcbtn{border-style:dashed;background:var(--card);padding:9px 14px}.vobtn.rcbtn .vomi{width:38px;height:38px;font-size:19px;background:color-mix(in srgb,var(--accent) 35%,var(--card))}`,document.head.appendChild(t)})();
