/*
  Ταμεία
  © 2026 Ανδρέας Μ. Γλεντζάκης (Andreas M. Glentzakis). Με την επιφύλαξη παντός δικαιώματος. All rights reserved.
  Απαγορεύεται η αντιγραφή, τροποποίηση και διάθεση, εν όλω ή εν μέρει, χωρίς προηγούμενη γραπτή άδεια του κατόχου.
  Copying, modification and distribution, in whole or in part, without the owner's prior written permission are prohibited.
*/
(function(){const t=document.createElement("style");t.textContent=`
.supbtn{display:flex;align-items:center;gap:10px;width:100%;padding:11px 14px;margin:0 0 12px;border-radius:14px;border:1.5px solid var(--line);background:var(--card);color:var(--ink);font-weight:800;font-size:15px;text-align:left}
.supbtn small{display:block;font-weight:600;color:var(--muted);font-size:12.5px}.supbtn .grow{flex:1}
.suprow{display:flex;gap:10px;align-items:center;padding:10px 12px;border-top:1px solid var(--line);cursor:pointer}
.suprow:first-child{border-top:0}.suprow .grow{min-width:0;flex:1}.suprow .title{font-weight:800}
.suprow .meta{font-size:12.5px;color:var(--muted);display:flex;gap:8px;flex-wrap:wrap}
.supq{display:inline-flex;gap:6px;flex:none}
.supq a{width:34px;height:34px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;font-size:16px;border:1.5px solid var(--line);background:var(--card)}
.supfs{border:1px solid var(--line);border-radius:14px;padding:4px 12px 12px;margin:12px 0;background:var(--card)}
.supfs h4{margin:10px 0 2px;font-size:14.5px}
.sup2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sup2 label{margin-top:6px}
.vatm{border:1.5px dashed var(--line);border-radius:12px;padding:8px 10px;margin:8px 0}
.vatmg{display:grid;grid-template-columns:52px 1fr;gap:6px 10px;align-items:center;margin-top:8px}
.vatmg label{margin:0;font-weight:800}.vatmg .note{grid-column:2;margin:-2px 0 4px;font-size:12px}
`,document.head.appendChild(t)})();const supList=()=>{const t=S.settings;return Array.isArray(t.sups)||(t.sups=[]),t.sups},supGet=t=>supList().find(o=>o.id===t),supByName=t=>supList().find(o=>norm(o.name)===norm(t||""));function supSpent(t){let o=0;try{allBookIds().forEach(a=>withBook(a,()=>(PB().ent||[]).forEach(r=>{r.dir==="out"&&r.cp&&norm(r.cp)===norm(t.name)&&(o+=+r.amount||0)})))}catch{}return rnd(o)}function supText(t){return[t.name,t.title,t.job,t.afm?T("ΑΦΜ")+": "+t.afm+(t.doy?" · "+T("ΔΟΥ")+": "+t.doy:""):"",[t.addr,[t.tk,t.city].filter(Boolean).join(" ")].filter(Boolean).join(", "),[t.phone,t.mobile].filter(Boolean).join(" · "),t.email,t.iban?"IBAN: "+t.iban:"",t.person?T("Υπεύθυνος")+": "+t.person:""].filter(Boolean).join(`
`)}function supPanelHTML(){const t=supList().length;return`<button type="button" class="supbtn" data-act="supOpen"><span style="font-size:24px">🏭</span><span class="grow">${T("Προμηθευτές")}<small>${t?pl(t,"{n} προμηθευτής","{n} προμηθευτές"):T("επωνυμία, ΑΦΜ, ΔΟΥ, διεύθυνση — για τα τιμολόγια")}</small></span><span class="note">›</span></button>`}function supSheet(t){pendingReopen=()=>supSheet(t),t=t||"";const o=supList().slice().sort((e,s)=>String(e.name).localeCompare(String(s.name),"el")),a=norm(t),r=a?o.filter(e=>norm([e.name,e.title,e.afm,e.city,e.job].join(" ")).includes(a)):o;openSheet({title:"🏭 "+T("Προμηθευτές"),cancelLabel:T("Κλείσιμο"),body:`
    ${o.length>5?`<input id="sp_q" type="search" placeholder="${T("Αναζήτηση…")}" value="${esc(t)}" autocomplete="off">`:""}
    ${r.length?panel(r.map(e=>{const s=String(e.mobile||e.phone||"").replace(/[^\d+]/g,"");return`<div class="suprow" data-sup="${e.id}">
      <div class="avatar">${esc((e.name||"?").trim().slice(0,2).toUpperCase())}</div>
      <div class="grow"><div class="title">${esc(e.name)}</div><div class="meta">${e.afm?`<span>${T("ΑΦΜ")} ${esc(e.afm)}</span>`:`<span style="color:var(--red)">${T("χωρίς ΑΦΜ")}</span>`}${e.city?`<span>${esc(e.city)}</span>`:""}${e.job?`<span>${esc(e.job)}</span>`:""}</div></div>
      ${s?`<span class="supq"><a href="tel:${esc(s)}" aria-label="${esc(T("Κλήση"))}">📞</a></span>`:""}</div>`}).join("")):`<div class="empty">${o.length?T("Δεν βρέθηκε."):T("Δεν έχεις βάλει ακόμα προμηθευτές.")}</div>`}
    <button type="button" class="btn amber wide" id="sp_new" style="width:100%;margin-top:10px">+ ${T("Νέος προμηθευτής")}</button>
    <button type="button" class="btn ghost wide" id="sp_ct" style="width:100%;margin-top:8px;border:1.5px solid var(--line)">📇 ${T("Νέος από τις επαφές")}</button>
    <p class="note">${T("Οι προμηθευτές εμφανίζονται στο «Προμηθευτής» κάθε εξόδου και περνάνε μόνοι τους επωνυμία και ΑΦΜ.")}</p>`});const p=$("#shBody");p.onclick=e=>{if(e.target.closest(".supq"))return;const s=e.target.closest("[data-sup]");s&&supForm(s.dataset.sup)},$("#sp_new").onclick=()=>supForm(null),$("#sp_ct").onclick=async()=>{const e=await supPick();e&&supForm(null,e)};const i=$("#sp_q");i&&(i.oninput=()=>{clearTimeout(i._t),i._t=setTimeout(()=>{supSheet(i.value);const e=$("#sp_q");e&&(e.focus(),e.setSelectionRange(e.value.length,e.value.length))},350)})}async function supPick(){if(!("contacts"in navigator)||!navigator.contacts||typeof navigator.contacts.select!="function")return toast(T("Αυτό το κινητό δεν δίνει τις επαφές σε εφαρμογές ιστού. Γράψε τα στοιχεία με το χέρι.")),null;try{let t=["name","tel","email"];try{const s=await navigator.contacts.getProperties();s&&s.includes("address")&&t.push("address")}catch{}const o=await navigator.contacts.select(t,{multiple:!1}),a=o&&o[0];if(!a)return null;const r=(a.tel||[]).map(s=>String(s).replace(/[^\d+]/g,"")).filter(Boolean),p=r.find(s=>/^(\+?30)?69/.test(s)),i=r.find(s=>s!==p),e=(a.address||[])[0]||{};return{name:(a.name||[])[0]||"",mobile:p||"",phone:i||!p&&r[0]||"",email:(a.email||[])[0]||"",addr:(e.addressLine||[]).join(" ")||"",tk:e.postalCode||"",city:e.city||""}}catch{return toast(T("Δεν άνοιξαν οι επαφές.")),null}}const SUP_F=[["name","Επωνυμία",""],["title","Διακριτικός τίτλος",""],["afm","ΑΦΜ","numeric"],["doy","ΔΟΥ",""],["job","Δραστηριότητα",""],["addr","Διεύθυνση",""],["tk","Τ.Κ.","numeric"],["city","Πόλη",""],["phone","Τηλέφωνο","tel"],["mobile","Κινητό","tel"],["email","Ηλεκτρονικό ταχυδρομείο","email"],["iban","IBAN",""],["person","Υπεύθυνος επικοινωνίας",""],["notes","Σημειώσεις",""]],SUP_TR=()=>[T("Επωνυμία"),T("Διακριτικός τίτλος"),T("ΑΦΜ"),T("ΔΟΥ"),T("Δραστηριότητα"),T("Διεύθυνση"),T("Τ.Κ."),T("Πόλη"),T("Τηλέφωνο"),T("Κινητό"),T("Ηλεκτρονικό ταχυδρομείο"),T("IBAN"),T("Υπεύθυνος επικοινωνίας"),T("Σημειώσεις")];function supForm(t,o){const a=t&&supGet(t),r=Object.assign({},a||{},o||{}),p=()=>supSheet(),i=(n,l)=>{const[,d,c]=SUP_F.find(m=>m[0]===n);return`<div><label for="sp_${n}">${T(d)}${n==="name"?" *":""}</label><input id="sp_${n}" ${c==="numeric"?'inputmode="numeric"':c==="tel"?'type="tel" inputmode="tel"':c==="email"?'type="email" inputmode="email"':""} ${n==="afm"?'maxlength="9"':""} value="${esc(r[n]||"")}" autocomplete="off"></div>`},e=a?supSpent(a):0;openSheet({title:a?"🏭 "+a.name:"🏭 "+T("Νέος προμηθευτής"),cancelLabel:T("Πίσω"),onCancel:p,saveLabel:a?T("Αποθήκευση"):T("Προσθήκη"),saveStyle:a?"primary":"amber",body:`
    <button type="button" class="kpick" id="sp_pick" style="float:right;margin-top:2px">📇 ${T("Από τις επαφές")}</button>
    ${a&&e>0?`<p class="note" style="margin-top:4px">${T("Έξοδα με αυτόν τον προμηθευτή")}: <b>${money(e)}</b></p>`:""}
    <div class="supfs" style="clear:both"><h4>🧾 ${T("Στοιχεία για το τιμολόγιο")}</h4>
      ${i("name")}<div class="sup2">${i("afm")}${i("doy")}</div>${i("title")}${i("job")}
      <p class="note accwarn" id="sp_afmw" hidden></p></div>
    <div class="supfs"><h4>📍 ${T("Διεύθυνση")}</h4>${i("addr")}<div class="sup2">${i("tk")}${i("city")}</div></div>
    <div class="supfs"><h4>📞 ${T("Επικοινωνία")}</h4><div class="sup2">${i("phone")}${i("mobile")}</div>${i("email")}${i("person")}</div>
    <div class="supfs"><h4>🏦 ${T("Πληρωμή")}</h4>${i("iban")}${i("notes")}</div>
    ${a?`<button type="button" class="btn ghost wide" id="sp_copy" style="width:100%;border:1.5px solid var(--line)">📋 ${T("Αντιγραφή στοιχείων")}</button>`:""}`,onSave:()=>{const n={};return SUP_F.forEach(([l])=>{n[l]=val("sp_"+l).trim()}),n.afm=n.afm.replace(/\D/g,""),n.iban=n.iban.replace(/\s+/g," ").toUpperCase(),n.name?supList().some(l=>l.id!==t&&(norm(l.name)===norm(n.name)||n.afm&&l.afm===n.afm))?(toast(T("Υπάρχει ήδη προμηθευτής με αυτή την επωνυμία ή αυτόν τον ΑΦΜ.")),!1):n.afm&&typeof afmOk=="function"&&!afmOk(n.afm)&&!confirm(T("Ο ΑΦΜ δεν φαίνεται σωστός. Να αποθηκευτεί έτσι;"))?!1:(a?Object.assign(a,n):supList().push(Object.assign({id:uid()},n)),persist(),render(),toast(a?T("Οι αλλαγές αποθηκεύτηκαν."):T("Προστέθηκε.")),p(),"replaced"):(toast(T("Γράψε την επωνυμία.")),!1)},onDelete:a?()=>(S.settings.sups=supList().filter(n=>n!==a),persist(),render(),p(),"replaced"):null,deleteMsg:T("Να διαγραφεί ο προμηθευτής; Τα έξοδα που έχεις γράψει μένουν.")});const s=()=>{const n=val("sp_afm").replace(/\D/g,""),l=$("#sp_afmw");l.hidden=!(n&&typeof afmOk=="function"&&!afmOk(n)),l.textContent=T("Ο ΑΦΜ δεν φαίνεται σωστός — έλεγξέ τον.")};$("#sp_afm").addEventListener("input",s),s(),$("#sp_pick").onclick=async()=>{const n=await supPick();if(n){val("sp_name").trim()&&n.name&&(n.person=n.name,delete n.name),Object.entries(n).forEach(([l,d])=>{const c=$("#sp_"+l);c&&d&&!c.value.trim()&&(c.value=d)}),sheetDirty=!0;try{sheetLive()}catch{}toast(T("Πέρασαν τα στοιχεία της επαφής."))}};const u=$("#sp_copy");u&&(u.onclick=async()=>{try{await navigator.clipboard.writeText(supText(a)),toast(T("Αντιγράφηκε."))}catch{navigator.share&&navigator.share({text:supText(a)}).catch(()=>{})}})}document.addEventListener("click",t=>{t.target.closest&&t.target.closest('[data-act="supOpen"]')&&(t.stopImmediatePropagation(),supSheet())},!0);
